### PR TITLE
Add default repo-id

### PR DESCRIPTION
**Pull request by tsmithv11**
# In This PR

Add default repo-id

https://github.com/bridgecrewio/checkov-vscode/issues/136

## Pictures/videos

- [x] I've reviewed my own code

### CODE REVIEW

**Review by mikeurbanski1 — APPROVED** [review]

**Comment by ultrajericho** [comment]
Maybe you should let us define the repo-id in the extension settings (or even allow it to be defined by folder/workspace) instead of forcing this "vscode" repo by default.

It should be a default value, but we should be able to override it.

**Comment by tsmithv11** [comment]
> Maybe you should let us define the repo-id in the extension settings (or even allow it to be defined by folder/workspace) instead of forcing this "vscode" repo by default.
> 
> It should be a default value, but we should be able to override it.
> 
> Because in the way we defined security in our Prisma Cloud instance, it just doesnt work with this default repo.

@ultrajericho thank you for the suggestion! The plugin does automatically add the repo-id if we can find it in the .git information. For defining your own repo-id, we currently don't support a way to define any setting per directory, so you would have to define one default repo for any directory we don't have the .git directory for. That is something we can look at doing in the future. For now, you can run a scan with the `vscode/default` repo-id and grant access to that repo in the developer role via Prisma Cloud.

**Comment by ultrajericho** [comment]
Ah, it's supposed to fetch .git? I didn't have that information. Thanks for your answer @tsmithv11 .

Still, it's strange because I have .git folders for those directories. Should I do something to give checkov access to this folder?
A priori, VSCode has access since I push/pull from the git interface in VSCode.

**Comment by tsmithv11** [comment]
@ultrajericho it should be available to the plugin if the root directory of the git repository was the folder that was opened.

**Pull request merged**
