### PR TITLE
Adding Framework/Skip-Framework functionality

### LINKED ISSUE #135: There is no support for the --framework or --skip-framework cli parameters
### Description

The VS Code extension does not have support for the `--skip-framework` or the `--framework` command line parameters. This prevents users from selectively utilizing or skipping specific frameworks. 

For a user who uses the Bridgecrew/Palo Alto API and does not subscribe to the SECRETS or SCA modules, this is important as without this functionality, `checkov` returns an error. 

#### Example: 
```
checkov.common.bridgecrew.platform_errors.ModuleNotEnabledError: ModuleNotEnabledError, The framework "secrets" is part of the "SECRETS" module, which is not enabled in the platform
```

### Solution

I have PR'd the code to address this in #134

### PR DESCRIPTION
**Pull request by billyjbryant**
# In This PR

- Added setting "Skip Frameworks" to take a space separated list of frameworks to skip during scanning
  - This results in the `checkov` cli command being appended with `--skip-framework <list of frameworks>` 
- Added setting "Framworks" to take a space separated list of frameworks to use during scanning
  - This results in the `checkov` cli command being appended with `--framework <list of frameworks>` 

#### Skip Frameworks 
skip-framework

#### Frameworks 
framework

## Usage:

```bash
[info]: Starting to scan. 
[debug]: Output: 
[info]: repo urlgit@github.com:mapbox/security-breakglass.git 
[info]: repo namemapbox/security-breakglass 
[info]: Running checkov: 
[info]: checkov --output-bc-ids -s --bc-api-key **** --repo-id mapbox/security-breakglass -f "/Users/billybryant/github/mapbox/security-breakglass/.github/workflows/bandit.yml" --skip-check BC_LIC* -o json --framework arm json github_actions cloudformation --skip-framework sca_package secrets sca_image 
[debug]: Checkov scan process exited with code 0 

... SCAN RESULTS ...
```

- [x] I've reviewed my own code

fixes #135

### CODE REVIEW

**Comment by billyjbryant** [comment]
Currently, only the last framework is skipped or included depending on the settings. I have opened https://github.com/bridgecrewio/checkov/issues/5486 for this issue.

**Comment by mikeurbanski1** [comment]
Hey @billyjbryant thanks for the contribution! I tested it locally and it looks good.

Can you please make one update to the help text for the setting, for both options? Add the line:

> You may need to run the extension command "Clear Checkov results cache" after modifying this setting.

**Review by SteveVaknin — APPROVED** [review]
@billyjbryant Thanks for your contribution! 🚀

**Comment by mikeurbanski1** [comment]
I went ahead and changed it. Merging.

**Review by mikeurbanski1 — APPROVED** [review]

**Pull request merged**
